[debug] [2020-03-31T21:36:57.896Z] ----------------------------------------------------------------------
[debug] [2020-03-31T21:36:57.897Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Student\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2020-03-31T21:36:57.897Z] CLI Version:   8.0.0
[debug] [2020-03-31T21:36:57.897Z] Platform:      win32
[debug] [2020-03-31T21:36:57.897Z] Node Version:  v13.11.0
[debug] [2020-03-31T21:36:57.898Z] Time:          Wed Apr 01 2020 00:36:57 GMT+0300 (Arabian Standard Time)
[debug] [2020-03-31T21:36:57.898Z] ----------------------------------------------------------------------
[debug] [2020-03-31T21:36:57.898Z] 
[debug] [2020-03-31T21:36:57.905Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-03-31T21:36:57.927Z] FetchError: Unexpected error determining execution environment: request to http://metadata.google.internal./computeMetadata/v1/instance failed, reason: getaddrinfo EAI_AGAIN metadata.google.internal.
    at ClientRequest.<anonymous> (C:\Users\Student\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at Socket.socketErrorListener (_http_client.js:432:9)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[error] 
[error] Error: An unexpected error has occurred.
